export const GET_PRODUCTS_RECORD_REQUEST = "GET_PRODUCTS_RECORD_REQUEST"
export const GET_PRODUCTS_RECORD_SUCCESS = "GET_PRODUCTS_RECORD_SUCCESS"
export const GET_PRODUCTS_RECORD_FAILURE = "GET_PRODUCTS_RECORD_FAILURE"

